window.cornerVideo = window.cornerVideo || {};
window.cornerVideo.params = {
	"video-width": 400,
	"video-width-mobile": 150,
	"video-position": "right",
	"transition-type": "grow",
	"transition-duration": 2000,
	"enable-close-button": true,
	"selecting-method": "auto-select",
	"position-vertical-offset": 20,
	"position-vertical-offset-mobile": 10,
	"position-side-offset": 20,
	"position-side-offset-mobile": 10,
	"enable-on-mobile": true,
	"mobile-breakpoint": 768,
	"enable-on-pause": true,
	"border-width": 0,
	"border-line": "solid",
	"border-color": "black",
	"box-shadow-x": 0,
	"box-shadow-y": 0,
	"box-shadow-blur": 16,
	"box-shadow-color": "#000088",
	"placeholder-bg-color": "#F6F6F6",
	"enable-cta": true,
	"cta-color": "#d76755",
	"cta-text-color": "#ffffff",
	"cta-border-radius": 6,
	"cta-border-width": 0,
	"cta-border-line": "solid",
	"cta-border-color": "black",
	"cta-box-shadow-x": 0,
	"cta-box-shadow-y": 0,
	"cta-box-shadow-blur": 16,
	"cta-box-shadow-color": "#000088",
	"cta-text": "Buy Now",
	"cta-url": "https://destinationlink.com",
	"cta-font-size": 24,
	"cta-padding": 16,
	"cta-margin": 23,
	"cta-font": "Poppins",
	"cta-color2": "#0398d3",
	"cta-target": "new-window"
};
